### ISSUE TITLE
Git LFS quota was exceeded

### ISSUE THREAD

**Issue by city0325** [dddavid4real/HistGen#10]
Hi,

I encountered an issue where the Git LFS quota was exceeded while trying to download the checkpoint. Is there an alternative way to download the file?

I need the dinov2_cpath_v1.pth file. Thank you!

Cloning into 'HistGen'...
remote: Enumerating objects: 467, done.
remote: Counting objects: 100% (371/371), done.
remote: Compressing objects: 100% (307/307), done.
Receiving objects: 100% (467/467), 74.41 MiB | 3.63 MiB/s, done. 96 (from 1)

Resolving deltas: 100% (78/78), done.
Downloading CLAM/models/ckpts/ctranspath.pth (111 MB)
Error downloading object: CLAM/models/ckpts/ctranspath.pth (7c99868): Smudge error: Error downloading CLAM/models/ckpts/ctranspath.pth (7c998680060c8743551a412583fac689db43cec07053b72dfec6dcd810113539): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: CLAM/models/ckpts/ctranspath.pth: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by dddavid4real** [comment]
Hi, thank you for reporting this issue.

I will upload the checkpoint to OneDrive as well to make sure the download is available. Please stay tuned.

**Comment by dddavid4real** [comment]
The model checkpoint has been synchronized to the OneDrive Sharepoint. Find it [here](https://hkustconnect-my.sharepoint.com/:f:/g/personal/zguobc_connect_ust_hk/EhmtBBT0n2lKtiCQt97eqcEBvO9WwNM3TL9x-7-kg_liuA).
