### ISSUE TITLE
 Coordinates or Relative Position of WSI Patch Features from DINOv2

### ISSUE THREAD

**Issue by casperliuliuliu** [dddavid4real/HistGen#17]
I’ve been exploring the provided image patch features and have been building a simple network to make use of them.

I have a question regarding the patch features: is it possible for you to provide the corresponding coordinates or relative positions of these patch features?

Having access to spatial relationship information would be incredibly helpful for various applications. However, since I don't have enough disk space to store all the WSIs, it is quite difficult to derive the spatial information directly from the original WSI. Is there any feasible way to obtain the relative positions of WSI patch features so I could reorder the features in 2D?

Thank you for your help!

**Comment by casperliuliuliu** [comment]
By the way, the region tokens are only used in the LGH encoder after feature extraction, so I assume the region tokens are added afterward.
Is it correct that the provided patch features from DINOv2 don't include any region token?

**Comment by dddavid4real** [comment]
Hi,

1. Yes we would like to provide the .h5 file that contains the coordinates of patches in the WSI. We will upload these files to the same HuggingFace repo. And it won't take long, please stay tuned.

2. Yes it's correct that the region tokens are added after feature extraction. The methodology figure might lead to ambiguity.

**Comment by dddavid4real** [comment]
Hi,

We have uploaded the .h5 files that contain coordinates of patches in each WSI. Please find the "h5_files.zip" file in the HuggingFace repo.

This issue will be closed and feel free to open new issue threads if you run into further problems.

**Comment by casperliuliuliu** [comment]
Thank you for your excellent work.
Once again, I am amazed by your efficiency! 🎉😮‍💨🙏
