### ISSUE TITLE
 Question about Ground Truth Preprocessing and Evaluation Metrics in the Paper

### ISSUE THREAD

**Issue by casperliuliuliu** [dddavid4real/HistGen#18]
Dear Authors,

Thank you for the great work on building a Benchmark! I have a few questions regarding the report preprocessing and evaluation process:

1.	In the paper, you mentioned:
“Since raw texts are still noisy and cluttered with redundant information, we utilize GPT-4 for further cleaning and summarization.” 
Could you clarify if the BLEU and METEOR scores in the comparison table are measured against the cleaned and summarized ground truth, or are they compared to the raw text? 
Additionally, is the annotation.json file in the provided dataset the cleaned and summarized ground truth used in the comparisons, or does it contain the raw text?

2.	Regarding the evaluation metrics:
Are all text tokens weighted equally during the measurement? Ground truth reports often contain a significant amount of template text shared across multiple reports, as well as information that might not be directly observable from a pathology WSI. In contrast, only a small portion of the text reflects patient-specific diagnostic details. Did you adjust the weighting or exclude the template parts and non-observable details when calculating the metrics to better focus on the diagnostic content?

Thank you for your time and for clarifying these points.

**Comment by dddavid4real** [comment]
Hi,

1. All measurement metrics are against the predicted reports and the annotation.json (ground truth, which is processed after GPT-4). But we do want to mention that the ground truth we provided still contains a lot of noise. So to make sure your model performs well and infers well, a good choice is to use LLMs such as ChatGPT, Qwen, etc., to further improve the clarity of the ground truth file.

2. That's a good point. But we measured all text tokens equally through BLEU, METEOR, and ROUGE-L scores. And I think future works should consider your suggestion to focus on more important texts.

**Comment by casperliuliuliu** [comment]
Thank you for clarifying! 
I agree that developing a diagnostic-specific evaluation could further improve generation quality. Keep up the great work!

**Comment by dddavid4real** [comment]
Totally agree. In chest X-ray report generation tasks, researchers normally divide measurement metrics into language quality evaluation (with BLEU, METEOR, etc.) and clinical efficacy evaluation (with F1 Score). Thus, I think in the field of histopathology report generation, there are a lot can be further explored and improved.
