### ISSUE TITLE
Request for Details and Code on Baselines

### ISSUE THREAD

**Issue by Loserm-Ricardo** [dddavid4real/HistGen#19]
Thank you for your remarkable contributions to the field of histopathology report generation. Given the limited research in this area and the scarcity of available datasets and code, your work and the publicly released resources are of immense value to advancing studies in this domain.

I am currently attempting to reproduce the results from your paper. As mentioned, there are few available report generation models, which makes the "SOTA models on WSI report generation" described in Table 1 of your paper particularly interesting.

I would like to better understand **how these classic models were adapted for the histopathology report generation task**. Could you kindly provide the code for the baselines used in your paper? Sharing these details would further propel research in this field and be greatly appreciated.

Thank you for your time and for sharing your excellent work with the community.

**Comment by Loserm-Ricardo** [comment]
My understanding is that these models were not specifically adapted for the task of histopathology report generation. Instead, it seems that these are standard report generation models, where features extracted from thousands of patches are directly fed into the model.
Could you confirm if my understanding is correct? Any additional details or clarification would be greatly appreciated.

**Comment by dddavid4real** [comment]
Hi,

Thank you for your interest. Indeed, these models (e.g., R2Gen, R2GenCMN) were originally designed for radiology report generations, where an input image is much smaller than a WSI (normally 512 x 512 pixels).

Thus, these models usually use full self-attention, which is no longer suitable for adaptation to WSI patches (thousands of patches lead to unaffordable computational overhead in full self-attention). Thus, to leverage them as baselines for histopathology report generation, one needs to first implement a token selection method for these models to screen the most useful patch tokens in the patch sequence to avoid the computational burden.

And in our experiment,  we tried uniform sampling and cross attention-based token compression.

We will include the codes for these baselines in the next coming week.

**Comment by dddavid4real** [comment]
Baseline methods are updated in the repo. Please check the instructions in README for details. This issue will be closed. Feel free to open new issue thread if you run into any problem.
