### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Andyfever123** [dddavid4real/HistGen#3]
Excuse me, may I ask you a question, what is the file size of WSI data set and dinov2_vitl used in your paper in G? And if you want to surface your paper with the data set in your paper, do you need a graphics card configuration? I have to evaluate whether the computer has enough memory. Are the conditions for the graphics card met?

**Comment by dddavid4real** [comment]
Hi. The dinov2_vitl feature files take around 322G and the original WSI data take around 7T space.
