### ISSUE TITLE
Weights for DINOv2 ViT-L Feature Extractor

### ISSUE THREAD

**Issue by BenPashley** [dddavid4real/HistGen#4]
Hi,

I'm really impressed with your work.  Where can I download the weights for your feature extractor? 

I can't see them on your downloads page.

Ben

**Comment by dddavid4real** [comment]
Thank you for your interest!

We are almost done with the organization of codes and checkpoints. The weight will be released **within one week**!

**Comment by dddavid4real** [comment]
We encourage you to download them from the TCGA data portal using the IDs we provided. The total file size is too large (~5T) and we haven't managed to find an online server to upload and save them efficiently. 

Besides, for experimental reproduction, the .pt files (features of these WSIs) are available and could be directly used as the model inputs.

**Comment by BenPashley** [comment]
Thanks.  I would like to replicate the full end to end process.  Are you able to share the data-prepartion code for the patching and DinoV2 feature extraction and preparation? I assume this includes the local/global hierarchical pre-processing of the features?

**Comment by dddavid4real** [comment]
The preprocessing process will be uploaded along with the DINOv2 feature extractor model.

For the preprocessing, we utilized an accelerated version of [CLAM](https://github.com/mahmoodlab/CLAM). Note that there is no hierarchical pre-processing included in our method. The preprocessing is the same as CLAM. The local-global hierarchical encoding is after the feature extraction and can be seen as a MIL model.

**Comment by dddavid4real** [comment]
Hi,

We have updated the code and checkpoints for preprocessing and feature extraction. This issue will be closed.

Feel free to re-open it if you run into problems.

**Comment by dddavid4real** [comment]
Hi,

We have updated the code and checkpoints for preprocessing and feature extraction. This issue will be closed.

Feel free to re-open it if you run into problems.
