### ISSUE TITLE
Issue pre-processing TCGA slides 

### ISSUE THREAD

**Issue by BenPashley** [dddavid4real/HistGen#7]
Hi,

I am following your instructions using your implementation of CLAM to extract the patches and generate the h5 files.  When I get to processing the larger slides, I get the following error.  

Maximum support image dimension is 65500

How did you manage to overcome this limitation using your CLAM implementation? As per the other issue, I am unable to download all of your pt files efficiently due to the download limitation of Sharepoint (although keen to repeat your process end to end).

Any help and guidance would be much appreciated!

Ben

**Comment by dddavid4real** [comment]
Hi, 

In the .sh script for patch segmenting, you could add this line of code at the start to mitigate this error:

`export OPENCV_IO_MAX_IMAGE_PIXELS=10995116277760`

Let me know if this works out.

**Comment by BenPashley** [comment]
Many thanks.  I managed to resolve the issue by replacing your version of wsi_core/WholeSlideImage.py from the CLAM repo.  That said, you mention that your version is accelerated.  Is there anything else I should consider with not using your version?

**Comment by dddavid4real** [comment]
Hi, main acceleration is implemented in the extract_features_fp.py file (used for feature extraction). If any error occurs during feature extraction, you could put back our original wsi_core/WholeSlideImage.py to try mitigating the errors.

Feel free to report any unexpected problems!
